=== s-ponkin/ParserXMLToJSON/target/classes/xsd-schema/users.xsd
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:types="types">
    <xs:import namespace="types.xsd" schemaLocation="types.xsd"/>
    <xs:element name="users">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="user" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element type="xs:string" name="firstName"/>
                            <xs:element type="xs:string" name="lastName"/>
                            <xs:element type="xs:string" name="middleName" minOccurs="0"/>
                            <xs:element type="types:nullableLong" name="inn" minOccurs="0"/>
                            <xs:element type="types:nullableLong" name="snils" minOccurs="0"/>
                            <xs:element type="xs:date" name="birthday" minOccurs="0"/>
                            <xs:element type="xs:string" name="login" minOccurs="0"/>
                            <xs:element type="xs:string" name="email"/>
                            <xs:element name="organizations">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="organization" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element type="types:nullableLong" name="inn"/>
                                                    <xs:element type="xs:string" name="kpp" minOccurs="0"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== s-ponkin/ParserXMLToJSON/src/main/resources/users.xml
<?xml version="1.0" encoding="UTF-8"?>
<users xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="file://../../../main/resources/xsd-schema/users.xsd">
    <user>
        <firstName>Иван</firstName>
        <lastName>Ургант</lastName>
        <middleName>Андреевич</middleName>
        <inn>909362680728</inn>
        <snils>64170687400</snils>
        <birthday>2020-01-02</birthday>
        <login>Login</login>
        <email>Email@test.ru</email>
        <organizations>
            <organization>
                <inn>9103602758</inn>
                <kpp>441244206</kpp>
            </organization>
            <organization>
                <inn>4626173053</inn>
            </organization>
        </organizations>
    </user>
    <user>
        <firstName>Господин</firstName>
        <lastName>Никто</lastName>
        <email>Email@test2.ru</email>
        <organizations>
            <organization>
                <inn>9103602758</inn>
                <kpp>441244206</kpp>
            </organization>
        </organizations>
    </user>
</users>
