=== s-ponkin/ParserXMLToJSON/target/classes/xsd-schema/user_profiles.xsd
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:types="types">
    <xs:import namespace="types" schemaLocation="types.xsd"/>
    <xs:element name="users">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="user" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element type="types:uuid" name="uuid"/>
                            <xs:element name="userProfiles">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="userProfile" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element type="types:nullableLong" name="organizationInn"/>
                                                    <xs:element type="xs:string" name="organizationKpp" minOccurs="0"/>
                                                    <xs:element type="xs:string" name="workEmail"/>
                                                    <xs:element type="xs:string" name="departmentName" minOccurs="0"/>
                                                    <xs:element type="xs:string" name="positionName" minOccurs="0"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== s-ponkin/ParserXMLToJSON/target/classes/user_profiles.xml
<?xml version="1.0" encoding="UTF-8"?>
<users xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="file://xsd-schema/user_profiles.xsd">
    <user>
        <uuid>0052f40b-e12f-4fcb-ac23-988c2b4f539b</uuid>
        <userProfiles>
            <userProfile>
                <organizationInn>3557421744</organizationInn>
                <organizationKpp>
                    043401207
                </organizationKpp>
                <workEmail>email.from.file@work.com</workEmail>
                <departmentName>Отдел</departmentName>
                <positionName>Должность</positionName>
            </userProfile>
            <userProfile>
                <organizationInn>4626173053</organizationInn>
                <organizationKpp>647074188</organizationKpp>
                <workEmail>email@work.com</workEmail>
            </userProfile>
        </userProfiles>
    </user>
    <user>
        <uuid>1152f40b-e12f-4fcb-ac23-988c2b4f539b</uuid>
        <userProfiles>
            <userProfile>
                <organizationInn>3557421744000</organizationInn>
                <organizationKpp>04340120</organizationKpp>
                <workEmail>other.email@work.com</workEmail>
            </userProfile>
        </userProfiles>
    </user>
</users>
