=== s-ponkin/ParserXMLToJSON/target/classes/xsd-schema/user_profile_roles.xsd
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:types="types">
    <xs:import namespace="types" schemaLocation="types.xsd"/>
    <xs:element name="userProfiles">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="userProfile" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element type="types:uuid" name="uuid"/>
                            <xs:element name="infoSystems">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="infoSystem" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element type="xs:string" name="techName"/>
                                                    <xs:element name="rolesToAdd" minOccurs="0">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="role" minOccurs="0"
                                                                            maxOccurs="unbounded">
                                                                    <xs:complexType>
                                                                        <xs:sequence>
                                                                            <xs:element type="xs:string"
                                                                                        name="techName"/>
                                                                            <xs:element type="xs:dateTime"
                                                                                        name="startDate"/>
                                                                            <xs:element type="xs:dateTime"
                                                                                        name="endDate"
                                                                                        minOccurs="0"/>
                                                                            <xs:element name="controlledInfoSystemTechName"
                                                                                        minOccurs="0">
                                                                                <xs:simpleType>
                                                                                    <xs:restriction base="xs:string">
                                                                                        <xs:minLength value="1"/>
                                                                                    </xs:restriction>
                                                                                </xs:simpleType>
                                                                            </xs:element>
                                                                        </xs:sequence>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element name="rolesToDelete" minOccurs="0">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="role" minOccurs="0"
                                                                            maxOccurs="unbounded">
                                                                    <xs:complexType>
                                                                        <xs:sequence>
                                                                            <xs:element type="xs:string"
                                                                                        name="techName"/>
                                                                        </xs:sequence>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== s-ponkin/ParserXMLToJSON/target/classes/user_profile_roles.xml
<?xml version="1.0" encoding="UTF-8"?>
<userProfiles xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:noNamespaceSchemaLocation="file://xsd-schema/user_profile_roles.xsd">
    <userProfile>
        <uuid>009e6b17-8974-484f-b0bb-b413c0d5ca20</uuid>
        <infoSystems>
            <infoSystem>
                <techName>not_xidbox</techName>
                <rolesToAdd>
                    <role>
                        <techName>information_system_manager </techName>
                        <startDate>2023-01-01T09:30:10Z</startDate>
                        <endDate>2023-12-01T10:31:09Z</endDate>
                        <controlledInfoSystemTechName>xidbox</controlledInfoSystemTechName>
                    </role>
                </rolesToAdd>
                <rolesToDelete>
                    <role>
                        <techName>
                            system_administrator
                        </techName>
                    </role>
                </rolesToDelete>
            </infoSystem>
        </infoSystems>
    </userProfile>
	<userProfile>
        <uuid>a41ec547-c9e0-447b-bf72-e9e2f570741f</uuid>
        <infoSystems>
            <infoSystem>
                <techName>xidbox_external_is</techName>
                <rolesToAdd>
                    <role>
                        <techName>account_manager </techName>
                        <startDate>2021-01-01T09:30:10Z</startDate>
                    </role>
                </rolesToAdd>
                <rolesToDelete>
                    <role>
                        <techName>
                            system_administrator
                        </techName>
                    </role>
                </rolesToDelete>
            </infoSystem>
        </infoSystems>
    </userProfile>
</userProfiles>
